services:
  authentification:
    build:
      context: authentification
    env_file:
      - .env
    ports:
      - "5001:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  match:
    build:
      context: ./match
    env_file:
      - .env
    ports:
      - "5003:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  api_gateway:
    build:
      context: ./api_gateway
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - authentification
      - match
    environment:
      - AUTHENTIFICATION_SERVICE_URL=${AUTHENTIFICATION_SERVICE_URL}
      - MATCH_SERVICE_URL=${MATCH_SERVICE_URL}

  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    ports:
      - "5002:5000"
    depends_on:
      - api_gateway
    environment:
      - API_GATEWAY_URL=${API_GATEWAY_URL}
    volumes:
      - ./frontend:/app/frontend

volumes:
  mysql_data:
