version: '3.8'

services:
  utilisateur:
    build:
      context: ./utilisateur
    env_file:
      - .env
    ports:
      - "5001:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  # ToDo : autres microservices

  api_gateway:
    build:
      context: ./api_gateway
    ports:
      - "5000:5000"
    depends_on:
      # ToDo : autres microservices
      - utilisateur

volumes:
  mysql_data:
